language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
install:
  - pip install -r requirements.txt --use-mirrors
  - python setup.py install
script:
  - cd tests
  - ls -al fixtures
  - ls -al fixtures/dummyrepo_with_many_remotes
  - ln -s ../startappsync startappsync
  - ln -s ../bin bin
  - nosetests
